# Generated by Django 6.0.2 on 2026-03-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astra_project', '0005_starsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetSatelliteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astra_project.planet')),
                ('satelliteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astra_project.satellite')),
            ],
        ),
    ]