# Generated by Django 6.0.2 on 2026-02-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('size', models.FloatField()),
                ('textureURL', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('speed', models.FloatField()),
                ('position', models.FloatField()),
            ],
        ),
    ]
