# Generated by Django 6.0.2 on 2026-03-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='textureURL',
        ),
        migrations.AddField(
            model_name='planet',
            name='pictureUrl',
            field=models.TextField(blank=True, help_text="URL to the planet's picture", null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='distance',
            field=models.FloatField(help_text='Distance from its star in million km'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='position',
            field=models.FloatField(help_text='A single value representing position. Consider expanding if this is for 3D space.'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='size',
            field=models.FloatField(help_text='Diameter in kilometers'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='speed',
            field=models.FloatField(help_text='Orbital speed in km/s'),
        ),
        migrations.AddField(
            model_name='planet',
            name='textureUrl',
            field=models.TextField(blank=True, help_text="URL to the planet's texture image", null=True),
        ),
    ]
