# Generated by Django 6.0.2 on 2026-03-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra_project', '0002_remove_planet_textureurl_planet_pictureurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('size', models.FloatField(help_text='Diameter in kilometers')),
                ('distance', models.FloatField(help_text='Distance from its planet in km')),
                ('textureUrl', models.TextField(blank=True, help_text="URL to the satellite's texture image", null=True)),
                ('pictureUrl', models.TextField(blank=True, help_text="URL to the satellite's picture", null=True)),
                ('speed', models.FloatField(help_text='Orbital speed in km/s')),
                ('position', models.FloatField(help_text='A single value representing position. Consider expanding if this is for 3D space.')),
            ],
        ),
    ]
