# Generated by Django 6.0.2 on 2026-03-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra_project', '0003_satellite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('size', models.FloatField(help_text='Diameter in kilometers')),
                ('distance', models.FloatField(help_text='Distance from Earth in light-years')),
                ('textureUrl', models.TextField(blank=True, help_text="URL to the star's texture image", null=True)),
                ('pictureUrl', models.TextField(blank=True, help_text="URL to the star's picture", null=True)),
                ('speed', models.FloatField(help_text='Relative speed in km/s')),
                ('position', models.FloatField(help_text='X coordinate in 3D space.')),
            ],
        ),
    ]