# Generated by Django 5.0.3 on 2024-03-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra_project', '0004_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('pictureUrl', models.TextField(blank=True, help_text="URL to the star system's picture", null=True)),
                ('distanceToUse', models.FloatField(help_text='Distance from Earth in light-years')),
            ],
        ),
    ]