# Generated by Django 6.0.2 on 2026-03-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astra_project', '0004_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='position',
            field=models.FloatField(help_text='A single value representing position.'),
        ),
    ]
