# Generated by Django 6.0.2 on 2026-03-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astra_project', '0005_alter_star_position'),
        ('astra_project', '0005_starsystem'),
    ]

    operations = [
    ]
