# Generated by Django 6.0.2 on 2026-03-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astra_project', '0007_starplanetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarSystemStarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starSystemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astra_project.starsystem')),
                ('starId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astra_project.star')),
            ],
        ),
    ]